
language: node_js
node_js:
  - "0.11"
before_install:
  - npm install -g grunt-cli
  - npm install -g git://github.com/vf1/flatten.git
install:
  - npm install --production
  - flatten-packages
  - npm install
before_script: grunt
script:
  - ls $TRAVIS_BUILD_DIR
  - ls $TRAVIS_BUILD_DIR/nw
deploy:
  skip_cleanup: true
  edge: true
  provider: releases
  api-key:
    - secure: kyFW7AYkAlhhvrIysuf2S0b1yLxpc/642stxuXpwW2WhABojDqOc5fJCXL0DQdrHP3w+D3w2oSMaYJvHEBBm0cLfQtBojVzle+8i+Of07Xl39P14mAjjbeNW+T/57hom2N0wwOGhksVuiUyjBnPf9QX5LPAWdOwZHAesMMN3dIM=
  file:
    - $TRAVIS_BUILD_DIR/nw/open-media-server-0.2.0.nw
    - $TRAVIS_BUILD_DIR/nw/open-media-server-0.2.0-linux-ia32.tar.gz
    - $TRAVIS_BUILD_DIR/nw/open-media-server-0.2.0-linux-x64.tar.gz
    - $TRAVIS_BUILD_DIR/nw/open-media-server-0.2.0-osx-ia32.zip
    - $TRAVIS_BUILD_DIR/nw/open-media-server-0.2.0-win-x86.zip
  on:
    tags: true
    all_branches: true
